# Generated by Django 3.2.14 on 2022-08-12 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movieapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='IMG',
            field=models.ImageField(default='hello', upload_to='gallery'),
            preserve_default=False,
        ),
    ]
